### ISSUE TITLE
1.21.1 neoforge please?

### ISSUE THREAD

**Issue by Rimplestilt** [KosmX/minecraftPlayerAnimator#115]
minecraftPlayerAnimator is required for Better combat and Combat roll to work. Those mods have 1.21.1 releases, this mod does not. I would really love a 1.21.1 update, as i had been using those in a shared modpack.

I had the mod working on my local modpack instance by simply changing the META-INF neoforge.mods.toml file to read  versionRange = "[1.21.1,)" which surprisingly worked without issues. I know a bit more will need changed for the build to work. I tried briefly, but the built jar file was not working for some reason. I thought i got the gradle settings right, but i get dozens of errors from the library files compiling.

But given 1 simple change to the jar file worked, i still think a 1.21 to 1.21.1 port should be a very simple change.

**Comment by krjencik** [comment]
i also want a a 1.21.1 neoforge version: the old one crashes
I need it for irons spells n spellbooks and irons gems n jewelry

**Comment by TheeMrCheeky** [comment]
![image](https://github.com/user-attachments/assets/dca6cb7a-3197-4d49-b82c-03bfbb5c2438)

These 2 work perfectly fine with either neoforge or fabric. My packs have over 250 mods and I have zero issues BUT yes I agree seeing this bumped to 1.21.1 for both would be very appreciated only because of the the curseforge app and exporting modpacks

**Comment by KosmX** [comment]
should be done
